import type { Metadata } from "next";
import {  Big_Shoulders, Great_Vibes, La_Belle_Aurore, Righteous, } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";


const greatVibes = Great_Vibes({
  variable: "--font-great-vibes",
  subsets: ["latin"],
  weight: "400",
})

const bigShoulders = Big_Shoulders({
  variable: "--font-big-shoulders",
  subsets: ["latin"],
  weight: "400",
})

const righteous = Righteous({
  variable: "--font-righteous",
  subsets: ["latin"],
  weight: "400",
})

const laBellaAuroea = La_Belle_Aurore({
  variable: "--font-la-belle-aurore",
  subsets: ["latin"],
  weight: "400",
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${laBellaAuroea.variable} ${righteous.variable} ${greatVibes.variable} ${bigShoulders.variable}  antialiased`}
      >
        <Toaster/>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
